import NavBar from "./components/NavBar"

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({ children }) {
//  return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }

export default function Layout () {
  return (
    <>
      <NavBar />
    </>
  )
}